# Generated by Django 5.1.6 on 2025-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.story'),
        ),
    ]
